### ISSUE TITLE
missmatched hatches

### ISSUE THREAD

**Issue by mhkim-swk** [dxfjs/writer#59]
Hi

when i try to plot Predefined "CROSS" hatch, 
but result was "CORK"

some other hatches were missmatched too.

in your code
https://github.com/dxfjs/writer/blob/fd22b111d49ff6805dc7d75550c748e6ebbda006/src/Internals/HatchPatterns.ts#L957:L990
135 degree lines are not required in cross pattern

please check this part, thanks!

+ and some patterns are broken when i scale them

**Comment by mhkim-swk** [comment]
![image](https://user-images.githubusercontent.com/88301397/208836339-b08779a4-0f5a-4ece-a589-64af0abd0867.png)

**Comment by tarikjabiri** [comment]
Hi,

Those pre-defined I auto generate them and I didn't test them, I am planing to get rid of them an make a way to define the pattern manually.

And add examples in docs so people can copy what they need only. Because  there's a lot of code shipped in the package and people don't use all of them or not using them at all.

Actually do you need them all.

**Comment by mhkim-swk** [comment]
@tarikjabiri 
It should be good
thats enough if user can define pattern.
i tried to find define custom pattern, but it seems impossible in currernt version.

thank you for comment!
happy new year

**Comment by mzaeemz** [comment]
@tarikjabiri any progress on this? Would love to have a method that accepts a .pat file and converts it into Hatch.

> Hi,
> 
> Those pre-defined I auto generate them and I didn't test them, I am planing to get rid of them an make a way to define the pattern manually.
> 
> And add examples in docs so people can copy what they need only. Because there's a lot of code shipped in the package and people don't use all of them or not using them at all.
> 
> Actually do you need them all.
